//! `SMPP` Fields.

/// Every field defined in the `SMPP` protocol and extra fields defined in this library.
///
/// Used for verbose error handling while decoding invalid pdus, if the `verbose` feature is enabled.
// TODO: example contains decoding the command defined in rusmpp
#[allow(non_camel_case_types)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum SmppField {
    addr,
    addr_npi,
    addr_ton,
    address_range,
    area,
    data_coding,
    dest_addr_npi,
    dest_addr_ton,
    dest_address,
    destination_addr,
    dl_name,
    encoding_content_type,
    error_code,
    error_status_code,
    esm_class,
    esme_addr,
    esme_addr_npi,
    esme_addr_ton,
    final_date,
    format,
    id,
    interface_version,
    message_id,
    message_payload,
    message_state,
    ms_availability_status,
    network_type,
    no_unsuccess,
    number_of_dests,
    number_of_time_units,
    password,
    pdu,
    priority_flag,
    protocol_id,
    registered_delivery,
    replace_if_present_flag,
    sc_interface_version,
    schedule_delivery_time,
    sequence_number,
    service_type,
    session_number,
    short_message,
    sm_default_msg_id,
    sm_length,
    source_addr,
    source_addr_npi,
    source_addr_ton,
    status,
    system_id,
    system_type,
    tag,
    tlvs,
    type_of_network,
    unit,
    units_of_time,
    unsuccess_sme,
    user_message_reference,
    validity_behavior,
    validity_information,
    validity_period,
    value,
    value_length,
}
