use rusmpp_macros::TlvValue;

use crate::{
    tlvs::{
        TlvTag,
        borrowed::{Tlv, TlvValue},
    },
    types::borrowed::{COctetString, OctetString},
    values::{
        bearer_type::BearerType, message_payload::borrowed::MessagePayload,
        sub_address::borrowed::Subaddress,
    },
};

#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord, TlvValue)]
pub enum MessageSubmissionRequestTlvValue<'a> {
    // AlertOnMessageDelivery(AlertOnMessageDelivery),
    BillingIdentification(OctetString<'a, 0, 1024>),
    // CallbackNum(OctetString<4, 19>),
    // CallbackNumAtag(OctetString<0, 65>),
    // CallbackNumPresInd(CallbackNumPresInd),
    // DestAddrNpCountry(OctetString<1, 5>),
    // DestAddrNpInformation(OctetString<0, 10>),
    // DestAddrNpResolution(DestAddrNpResolution),
    // DestAddrSubunit(AddrSubunit),
    DestBearerType(BearerType),
    // DestNetworkId(COctetString<7, 66>),
    // DestNetworkType(NetworkType),
    // DestNodeId(OctetString<6, 6>),
    // DestSubaddress(Subaddress),
    // DestTelematicsId(u16),
    // DestPort(u16),
    // DisplayTime(DisplayTime),
    // ItsReplyType(ItsReplyType),
    // ItsSessionInfo(ItsSessionInfo),
    // LanguageIndicator(LanguageIndicator),
    MessagePayload(MessagePayload<'a>),
    // MoreMessagesToSend(MoreMessagesToSend),
    // MsMsgWaitFacilities(MsMsgWaitFacilities),
    // MsValidity(MsValidity),
    // NumberOfMessages(NumberOfMessages),
    // PayloadType(PayloadType),
    // PrivacyIndicator(PrivacyIndicator),
    // QosTimeToLive(u32),
    // SarMsgRefNum(u16),
    // SarSegmentSeqnum(u8),
    // SarTotalSegments(u8),
    // SetDpf(SetDpf),
    // SmsSignal(u16),
    // SourceAddrSubunit(AddrSubunit),
    // SourceBearerType(BearerType),
    // SourceNetworkId(COctetString<7, 66>),
    // SourceNetworkType(NetworkType),
    // SourceNodeId(OctetString<6, 6>),
    // SourcePort(u16),
    SourceSubaddress(Subaddress<'a>),
    // SourceTelematicsId(u16),
    // UserMessageReference(UserMessageReference),
    UserResponseCode(u8),
    // UssdServiceOp(UssdServiceOp),
}
