services:
  rusmpps:
    container_name: rusmpps
    image: jadkhaddad/rusmpps:latest
    environment:
      - RUSMPPS_CONFIG_FILE=/etc/rusmpps/config.yaml
    ports:
      - "2775:2775"
    restart: unless-stopped
    volumes:
      - ./config.yaml:/etc/rusmpps/config.yaml:ro

  tls-upstream:
    container_name: tls-upstream
    image: jadkhaddad/tls-upstream:latest
    command:
      - "--config-file"
      - "/etc/tls-upstream/config.yaml"
    ports:
      - "2776:2776"
    restart: unless-stopped
    volumes:
      - ./tls-upstream-config.yaml:/etc/tls-upstream/config.yaml:ro
      - /opt/caddy/mnt/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/rusmpps.rusmpp.org/rusmpps.rusmpp.org.crt:/etc/tls-upstream/cert.pem:ro
      - /opt/caddy/mnt/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/rusmpps.rusmpp.org/rusmpps.rusmpp.org.key:/etc/tls-upstream/key.pem:ro
