runtime: CurrentThread
dns_resolver: Hickory
hosts:
  - addr: 0.0.0.0:2776
    kind: Tls
    certs:
      certs: "/etc/upstream/cert.pem"
      key: "/etc/upstream/key.pem"
      watch:
        kind: Debounce
        duration: 2s
    upstreams:
      - domain: rusmpps
        port: 2775
        kind: Tcp